// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwoE-6qeF25Me_MTgLWS_4gHRhe7Bw2Jc',
    appId: '1:182552086703:web:0e2a14ca1fedaf67a7ac5a',
    messagingSenderId: '182552086703',
    projectId: 'employeeapp-b7479',
    authDomain: 'employeeapp-b7479.firebaseapp.com',
    databaseURL: 'https://employeeapp-b7479-default-rtdb.firebaseio.com',
    storageBucket: 'employeeapp-b7479.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4TWxMK97rFwDfF0LaYcJIQeGJguZsa-s',
    appId: '1:182552086703:android:7d6e21b83c97c320a7ac5a',
    messagingSenderId: '182552086703',
    projectId: 'employeeapp-b7479',
    databaseURL: 'https://employeeapp-b7479-default-rtdb.firebaseio.com',
    storageBucket: 'employeeapp-b7479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2xLxVLcHEkoRPpR6-hpnnfp4vk0dNqpo',
    appId: '1:182552086703:ios:aceecab1a9e0fb0da7ac5a',
    messagingSenderId: '182552086703',
    projectId: 'employeeapp-b7479',
    databaseURL: 'https://employeeapp-b7479-default-rtdb.firebaseio.com',
    storageBucket: 'employeeapp-b7479.appspot.com',
    androidClientId: '182552086703-0epv0748doa26qpugaq02u9e2btdq80p.apps.googleusercontent.com',
    iosClientId: '182552086703-bjvc1mobdi73ahld669ho36r2ncr3svm.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2xLxVLcHEkoRPpR6-hpnnfp4vk0dNqpo',
    appId: '1:182552086703:ios:c052374859b55352a7ac5a',
    messagingSenderId: '182552086703',
    projectId: 'employeeapp-b7479',
    databaseURL: 'https://employeeapp-b7479-default-rtdb.firebaseio.com',
    storageBucket: 'employeeapp-b7479.appspot.com',
    androidClientId: '182552086703-0epv0748doa26qpugaq02u9e2btdq80p.apps.googleusercontent.com',
    iosClientId: '182552086703-21h7ef57jqtlu3l6cv62hud3hg1kjcvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeapp.RunnerTests',
  );
}
